version: "3.9"
services:
  db:
    image: postgres
    restart: always
    container_name: db
    env_file:
      - ../.env
   # environment:
   ##   POSTGRES_USER: postgres
    #  POSTGRES_PASSWORD: postgres
     # POSTGRES_DB: disgram
    ports:
      - '5432:5432'
    volumes:
      - disgram:/var/lib/postgresql/data

  disgram:
    build:
       context: ../
       dockerfile: ./docker/Dockerfile
    #environment:
  #    DB_SCHEMA: postgres
  #    DB_USER: postgres
  #    DB_PASSWORD: postgres
 #     DB_NAME: disgram
    depends_on:
      - db

volumes:
  disgram:
