version: "3.9"
services:
  db:
    image: postgres
    restart: always
    container_name: db
    env_file:
      - ../.env
    ports:
      - '5432:5432'
    volumes:
      - disgram:/var/lib/postgresql/data

  disgram:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      - PG_HOST=db
      - NODE_ENV=production
    depends_on:
      - db
    restart: always

volumes:
  disgram:
