include:
  - infrastructure-services.yml
services:
  disgram:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      - PG_HOST=db
      - RABBITMQ_HOST=rabbitmq
      - NODE_ENV=production
    depends_on:
      - db
      - rabbitmq
    restart: always