services:
  db:
    image: postgres
    restart: always
    container_name: db
    env_file:
      - ../.env
    ports:
      - '5433:5432'
    volumes:
      - disgram:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    env_file:
      - ../.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    restart: always
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management plugin
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

volumes:
  disgram:
  rabbitmq_data:
  pgadmin-data:
